### ISSUE TITLE
Revisão sobre Estrutura Sequencial

### ISSUE THREAD

**Issue by rochajario** [lucasdesouza2/Desenvolvimento-Java#1]
- [x] Exercício 1;
- [x] Exercício 2;
- [x] Exercício 3;
- [x] Exercício 4.

**Comment by lucasdesouzax** [comment]
Exercícios concluídos, embora tenha usado conceitos bem assimilados as equações propostas no exercício 1 exigiram um pouco de raciocínio lógico haha. Obs: o exercício 4 é quase idêntico ao exercício 3 a única diferença é que no 4 é calculado o peso ideal também para pessoas do sexo feminino. Por esse motivo deixei apenas 3 opções no código.

**Comment by lucasdesouza2** [comment]
Obs: o exercício 4 é quase idêntico ao exercício 3 a unica diferença é que no 4 é calculado o peso ideal também para pessoas do sexo feminino.
